---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - bat
  - exa
  - ghostscript
  - git-delta
  - neovim
  - nvm
  - python@3.8
  - ripgrep
  - rust-analyzer
  - rustup-init
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

hombrew_cask_apps:
  - firefox
  - google-chrome
  - iterm2
  - mactex
  - scroll-reverser
  - spotify
  - visual-studio-code
  - font-fira-code
  - insomnia
  - macfuse
  - pgadmin4
  - slack
  - the-unarchiver
  - zoom

npm_packages:
  - "@nestjs/cli"
  - eslint
  - neovim
  - prettier
  - serve
  - tslib
  - typescript-language-server
  - typescript
  - vscode-langservers-extracted
  - yaml-language-server
  - yarn
