---
- name: Get the path to ZSH
  become: false
  delegate_to: localhost
  command: which zsh
  register: zsh_path
  changed_when: false

- name: "Ensure zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true

- name: Ensure Oh My ZSH is installed
  shell: yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

- name: Ensure autouggestions are installed
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions 
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    recursive: no
    force: yes

- name: Ensure p10k is installed
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
    force: yes

- name: Set ZSH as the default shell
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true
  changed_when: false
